### PR TITLE
Register PGDG dependencies in install scripts

### LINKED ISSUE #8: Install fails on CentOS 7.2 / Fedora 24
Starting from a fresh machine this is what happens.

``` bash
$ curl https://install.citusdata.com/community/rpm.sh | sudo bash
# etc etc

$ sudo yum install citus_95
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirrors.evowise.com
 * extras: mirror.supremebytes.com
 * updates: mirror.supremebytes.com
Resolving Dependencies
--> Running transaction check
---> Package citus_95.x86_64 0:5.2.0-0.1.rc.1.el7.centos will be installed
--> Processing Dependency: postgresql95-server for package: citus_95-5.2.0-0.1.rc.1.el7.centos.x86_64
--> Processing Dependency: libpq.so.5()(64bit) for package: citus_95-5.2.0-0.1.rc.1.el7.centos.x86_64
--> Running transaction check
---> Package citus_95.x86_64 0:5.2.0-0.1.rc.1.el7.centos will be installed
--> Processing Dependency: postgresql95-server for package: citus_95-5.2.0-0.1.rc.1.el7.centos.x86_64
---> Package postgresql-libs.x86_64 0:9.2.15-1.el7_2 will be installed
--> Finished Dependency Resolution
Error: Package: citus_95-5.2.0-0.1.rc.1.el7.centos.x86_64 (citusdata_community)
           Requires: postgresql95-server
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

If I then try yum installing `postgresql95-server` it can't find the package.

---

Fedora 24 also fails to find that dependency:

``` bash
$ sudo yum install citus_95
Yum command has been deprecated, redirecting to '/usr/bin/dnf install citus_95'.
See 'man dnf' and 'man yum2dnf' for more information.
To transfer transaction metadata from yum to DNF, run:
'dnf install python-dnf-plugins-extras-migrate && dnf-2 migrate'

Failed to synchronize cache for repo 'citusdata_community-source', disabling.
Last metadata expiration check: 0:00:07 ago on Tue Aug  9 23:47:22 2016.
Error: nothing provides postgresql95-server needed by citus_95-5.1.1-1.fc24.x86_64
(try to add '--allowerasing' to command line to replace conflicting packages)
```

Another thing to note: Fedora appears to want to install 5.1 whereas CentOS is on 5.2 RC 1.

### PR DESCRIPTION
**Pull request by begriffs**
With this change the user will be able to immediately install postgresql-9.5-citus or citus_95 after running the Citus community installer for their Linux.

Fixes #8 

Notes
- Installers are still idempotent
- deb.sh now creates `/etc/apt/sources.list.d/pgdg.list` and will _overwrite_ it if it exists. Theoretically it might clobber a user file, but it seems unlikely
- Not sure what happens if the system had an older postgres version already installed, should I test this?
- RPM version has a check to deal with 32bit systems although IIRC we don't have a Citus package created for this yet. It's for future proofing.

@jasonmp85 could give these scripts one more test in your battery of Docker containers?

### CODE REVIEW

**Comment by lfittl** [comment]
@begriffs Re: `Not sure what happens if the system had an older postgres version already installed, should I test this?` - this seems like it could potentially be a problem if someone has an existing PostgreSQL cluster that they want to add the citus extension too.

My assumption is that this might force their hand into an upgrade to PostgreSQL 9.5 - which is needed for Citus, but might not be obvious from the instructions. Can we add a easily noticable warning that we're doing this? (auto-adding PGDG)

File: community/deb.sh [hunk 1]
```diff
@@ -79,10 +79,19 @@ detect_os ()
   echo "Detected operating system as $os/$dist."
 }
 
+add_pgdg ()
+{
+  echo "Registering PostgreSQL PGDG dependencies..."
+  echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list
+  apt-get install wget ca-certificates
+  wget --quiet --no-check-certificate -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
```
Comment (jasonmp85) [inline community/deb.sh]: Eeeehhh, a dependency on _both_ `curl` _and_ `wget`? We should change this to `curl`.

Comment (begriffs) [inline community/deb.sh]: Good catch, I lifted that from a snippet I had in the docs.

File: community/deb.sh [hunk 2]
```diff
@@ -79,10 +79,19 @@ detect_os ()
   echo "Detected operating system as $os/$dist."
 }
 
+add_pgdg ()
+{
+  echo "Registering PostgreSQL PGDG dependencies..."
+  echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list
```
Comment (jasonmp85) [inline community/deb.sh]: I feel a _little_ uneasy blasting over this file without checking first. I know this script also blasts over the packagecloud file, but we "own" that one. This one could already be there on a user's machine.

File: community/deb.sh [hunk 3]
```diff
@@ -79,10 +79,19 @@ detect_os ()
   echo "Detected operating system as $os/$dist."
 }
 
+add_pgdg ()
```
Comment (jasonmp85) [inline community/deb.sh]: I think I'd like to verify whether `postgresql-9.5` is available before adding the repository. Looking into how to do this…

Comment (jasonmp85) [inline community/deb.sh]: Ok, in Debian:

``` sh
apt-cache show postgresql-9.5 2> /dev/null
```

This prints stuff about the available package to stdout. Can capture to a variable and test for empty string, or use exit code.

File: community/rpm.sh [hunk 4]
```diff
@@ -78,10 +78,39 @@ detect_os ()
   echo "Detected operating system as ${os}/${dist}."
 }
 
+add_pgdg ()
```
Comment (jasonmp85) [inline community/rpm.sh]: And checking this in Red Hat is:

``` sh
yum list -q postgresql95-server 2>/dev/null
```

Again, can check for empty string or use exit code.

File: community/rpm.sh [hunk 5]
```diff
@@ -78,10 +78,39 @@ detect_os ()
...
+  fi
+
+  if [[ "$(arch)" = "x86_64" ]]; then
+    arch="x86_64"
+  else
+    # sometimes reports as i686
+    arch="i386"
+  fi
+
+  yum install -y https://download.postgresql.org/pub/repos/yum/9.5/$family/$family_short-$dist-$arch/pgdg-${pkg_os}95-9.5-$suffix.noarch.rpm
```
Comment (jasonmp85) [inline community/rpm.sh]: This is _super_ long. Maybe break across several lines, building it up via appends?

File: community/deb.sh (hunk 3 above)
Comment (jasonmp85) [inline community/deb.sh]: Also, out of analogy to `curl_check`, I think we should call this `pgdg_check`.

File: community/deb.sh [hunk 6]
```diff
@@ -79,10 +79,19 @@ detect_os ()
...
+  echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list
+  apt-get install ca-certificates
+  curl -L https://www.postgresql.org/media/keys/ACCC4CF8.asc 2> /dev/null | apt-key add - &>/dev/null
+}
+
 main ()
 {
   detect_os
   curl_check
+  add_pgdg
```
Comment (jasonmp85) [inline community/deb.sh]: Since I'd like to add a `postgresql-9.5` availability check in here, let's move this after the _Running apt-get update_ phase.

Comment (jasonmp85) [inline community/deb.sh]: Here are the three scenarios I envision, as seen by the user:

# Debian

## PostgreSQL 9.5 Found

```
Checking for postgresql-9.5...
Detected postgresql-9.5...
# no further PGDG-related output
```

## PostgreSQL 9.5 Not Found, `pgdg.list` File Absent

```
Checking for postgresql-9.5...
Installing PostgreSQL Apt Repository (PGDG)...
# no further PGDG-related output
```

## PostgreSQL 9.5 Not Found, `pgdg.list` File Present

```
Checking for postgresql-9.5...
Unable to install PostgreSQL Apt Repository

The file /etc/apt/sources.list.d/pgdg.list already exists.

Contact engage@citusdata.com with information about your system for help.
# exit with status 1
```

# Red Hat

## PostgreSQL 9.5 Found

```
Checking for postgresql95-server...
Detected postgresql95-server...
# no further PGDG-related output
```

## PostgreSQL 9.5 Not Found

```
Checking for postgresql95-server...
Installing PostgreSQL Yum Repository (PGDG)...
# no further PGDG-related output
```

File: community/deb.sh [hunk 7]
```diff
@@ -79,17 +79,47 @@ detect_os ()
...
+The file $pgdg_list already exists.
+
+Contact engage@citusdata.com with information about your system for help.
+
+EOM
+      exit 1
+    fi
+
+    echo "Installing PostgreSQL Apt Repository (PGDG)..."
+    echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > $pgdg_list
```
Comment (begriffs) [inline community/deb.sh]: Ran into an awkward thing. If the `lsb-release` package is not installed prior to running this script then the `$dist` variable is set to 8, otherwise to `jessie`. We need the codename when running the deb command. One solution is to install the package prior to running `detect_os`...

**Comment by sumedhpathak** [comment]
I tried just running the rpm.sh script on Amazon Linux. It doesn't appear to successfully install the PGDG repository. 

Possibly relevant error:

```
Loaded plugins: priorities, update-motd, upgrade-helper
Cannot open: https://download.postgresql.org/pub/repos/yum/9.5/redhat/rhel-2016-x86_64/pgdg-amzn95-9.5-2.noarch.rpm. Skipping.
Error: Nothing to do
Downloading repository file: https://repos.citusdata.com/community/config_file.repo?os=amzn&dist=2016&source=script
done.
```

I also get this error at the bottom:

```
Importing GPG key 0x1530DF18:
 Userid     : "https://packagecloud.io/citusdata/community (https://packagecloud.io/docs#gpg_signing) <support@packagecloud.io>"
 Fingerprint: e6ff c1a8 e256 1fc0 04d1 847f 56f4 fa44 1530 df18
 From       : https://repos.citusdata.com/community/gpgkey
https://repos.citusdata.com/community/el/6/x86_64/repodata/repomd.xml: [Errno -1] repomd.xml signature could not be verified for citusdata_community
Trying other mirror.


 One of the configured repositories failed (citusdata_community),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Disable the repository, so yum won't use it by default. Yum will then
        just ignore the repository until you permanently enable it again or use
        --enablerepo for temporary usage:

            yum-config-manager --disable citusdata_community

     4. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=citusdata_community.skip_if_unavailable=true

failure: repodata/repomd.xml from citusdata_community: [Errno 256] No more mirrors to try.
```

However, it does seem to have installed our packageCloud repo. When I try install citus_95 however, it fails since PGDG itself wasn't set up:

```
[ec2-user@ip-10-142-209-58 ~]$ sudo yum install citus_95
Loaded plugins: priorities, update-motd, upgrade-helper
Resolving Dependencies
--> Running transaction check
---> Package citus_95.x86_64 0:5.2.0-0.1.rc.1.el6 will be installed
--> Processing Dependency: postgresql95-server for package: citus_95-5.2.0-0.1.rc.1.el6.x86_64
--> Processing Dependency: libpq.so.5()(64bit) for package: citus_95-5.2.0-0.1.rc.1.el6.x86_64
--> Running transaction check
---> Package citus_95.x86_64 0:5.2.0-0.1.rc.1.el6 will be installed
--> Processing Dependency: postgresql95-server for package: citus_95-5.2.0-0.1.rc.1.el6.x86_64
---> Package postgresql8-libs.x86_64 0:8.4.20-5.52.amzn1 will be installed
--> Finished Dependency Resolution
Error: Package: citus_95-5.2.0-0.1.rc.1.el6.x86_64 (citusdata_community)
           Requires: postgresql95-server
```

If I manually first install PGDG via our current documentation instructions, then run rpm.sh, I am able to update Citus 5.1 to Citus 5.2-rc1 package. This works fine.

**Comment by sumedhpathak** [comment]
We generate the PGDG repo string as:

```
https://download.postgresql.org/pub/repos/yum/9.5/redhat/rhel-2016-x86_64/pgdg-amzn95-9.5-2.noarch.rpm
```

However, the PostgreSQL installation page has the repo URL as:

```
https://download.postgresql.org/pub/repos/yum/9.5/redhat/rhel-6-x86_64/pgdg-ami201503-95-9.5-2.noarch.rpm
```

**Comment by sumedhpathak** [comment]
@begriffs and I have been testing the script. I've tested so far on:
Ubuntu: 12.04, 14.04 and 16.04. I also tested on Amazon Linux. I'm able to:
- Fresh install Citus 5.2 and PostgreSQL 9.5.4 via the script.
- Install PostgreSQL 9.5.4 and Citus 5.1 via PGDG, run the script, and then upgrade to Citus 5.2 using our minor version upgrade instructions.
- Install PostgreSQL 9.4 and Citus 5.1 in parallel with PostgreSQL 9.5 and Citus 5.2.

One note: On Amazon Linux we don't seem to have citus_94 packages available. However they do exist in the Ubuntu PGDG repo's. Joe mentioned the same for CentOS and RHEL as well. Any reason why we don't have the 9.4 supported packages in the RHEL repo's?

**Comment by begriffs** [comment]
I successfully tested a fresh install on
- CentOS 6 & 7
- Oracle Linux 7
- Debian Jessie & Wheezy

I also tested first installing `postgresql-9.4-citus` on the Debians and then running the packagecloud script and installing `postgresql-9.5-citus`. This worked and I was able to run commands from the _Distributed Tables → Hash Distribution_ section of the docs on the cluster. Both versions of Postgres coexist in different directories.

**Comment by begriffs** [comment]
Had a problem when running the script on RHEL 7:

```
Detected operating system as rhel/7.
Checking for curl...
Detected curl...
Checking for postgresql95-server...
Installing pgdg95 repo... Cannot open: https://download.postgresql.org/pub/repos/yum/9.5/redhat/rhel-7-x86_64/pgdg-rhel95-9.5-2.noarch.rpm. Skipping.
Error: Nothing to do
done.
Downloading repository file: https://repos.citusdata.com/community/config_file.repo?os=rhel&dist=7&source=script... done.
Installing pygpgme to verify GPG signatures... done.
Installing yum-utils... done.
Generating yum cache for citusdata_community... done.

The repository is set up! You can now install packages.
```

Looks like this would fix it

``` diff
-https://download.postgresql.org/pub/repos/yum/9.5/redhat/rhel-7-x86_64/pgdg-rhel95-9.5-2.noarch.rpm
+https://download.postgresql.org/pub/repos/yum/9.5/redhat/rhel-7-x86_64/pgdg-redhat95-9.5-2.noarch.rpm
```

I'm experimenting with changing `$pkg_os` in the rhel case and will add my commit if it works.

**Comment by jasonmp85** [comment]
> Looks like this would fix it

Ah, a hasty refactoring on my part. I started out with a very explicit `switch` block but later removed what looked redundant among all the cases. Should be a quick fix.

**Comment by begriffs** [comment]
That fixed rhel 7!

On rhel 6 I get:

```
Detected operating system as redhatenterpriseserver/6.
Unfortunately, your operating system distribution and version are not supported by this script.
```

Also it's using the lsb_release conditional branch to detect that:

``` bash
$ lsb_release -i
Distributor ID: RedHatEnterpriseServer
```

On rhel 7 it uses os-release

``` bash
$ . /etc/os-release
$ echo $ID
rhel
```

**Comment by begriffs** [comment]
Tested that this also works on Amazon Linux `2015.03`, `2015.09`, and `2016.03`

**Comment by jasonmp85** [comment]
Is there anything else to be done here, or are we close to ready?

**Comment by jasonmp85** [comment]
@sumedhpathak, @begriffs, is this a :shipit:?

If so, I'll squash the commits and make sure the other files have the changes we've put into the community one.

**Comment by sumedhpathak** [comment]
So it now works on RHEL as well? If so, I think its a 🚢

**Comment by sumedhpathak** [comment]
Could you let us know once its merged and deployed (?) to install.citusdata.com?

**Comment by begriffs** [comment]
Looks good to me as well. Once it's merged I'll test the new installation docs and merge that too.
